#!/usr/bin/env bash

set -eo pipefail

echo "Basic lint check"
echo "..."
go vet ./...

echo "Run formatter"
echo "..."
if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
    gofmt -l .
    exit 1
fi

echo "Check if stuff is tidy"
echo "..."
go mod tidy
git diff --exit-code -- go.mod go.sum

echo "Ensure tests pass before committing"
echo "..."
go test ./...
