name: Release Go Binary

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - uses: actions/checkout@v3
    - run: go test ./internal

  cleanup:
    permissions:
      contents: write  # for mknejp/delete-release-assets to delete release assets
    runs-on: ubuntu-latest
    steps:
    - name: Delete old release assets
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ github.token }}
        tag: dev
        fail-if-no-assets: false
        assets: |
          goke-*

  build-binaries:
    permissions:
      contents: write
    releases-matrix:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          goos: [linux, windows, darwin]
          goarch: ["386", amd64, arm64]
          exclude:
            - goarch: "386"
              goos: darwin
            - goarch: arm64
              goos: windows
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.31
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./cmd/cli"
        binary_name: "goke"
        extra_files: LICENSE README.md